### ISSUE TITLE
netlink nkernel.c wont compile with newer kernels then 2.6

### ISSUE THREAD

**Issue by ayeks** [mdcb/kernel-howto#1]
The nkernel.c wont compile with newer kernels because struct genl_info has no member named 'snd_pid' and the functions 'genl_register_ops', 'genl_unregister_ops' are missing.

[genetlink.h?v=2.6.32](http://lxr.free-electrons.com/source/include/net/genetlink.h?v=2.6.32)
[genetlink.h?v=3.13](http://lxr.free-electrons.com/source/include/net/genetlink.h?v=3.13)

I was not able to find any example of an working kernel-to-usermode netlink communication with an current kernel. I gave it a try to fix your implementation to match the kernel changes.

snd_pid was changed to snd_portid [Change 2012/09/08](http://lists.openwall.net/netdev/2012/09/08/4).

genl_register_ops is not longer existent. So I used genl_register_family_with_ops. It is not possible to pass the ops as pointer. If you try that gcc returns `error: negative width in bit-field '<anonymous>'` while calling ARRAY_SIZE(ops) in genetlink.h.
The solution is to define the ops as a static array. 

There is no genl_unregister_ops function in the newer kernels. So I just left it out. With these changes your example is working with newer kernels. I tried it with 4.2.0

I will upload a pull request tomorrow.

**Comment by mdcb** [comment]
closes #1
